[workspace]
resolver = "2"
members = ["bin/*", "contracts"]

[workspace.dependencies]
alloy = { version = "0.3.1", default-features = false, features = ["json"] }
anyhow = "1.0.86"
foundry-compilers = "0.11.0"
tokio = { version = "1.39.1", features = ["full"] }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
