[workspace]
resolver = "2"
members = ["bin/*", "contracts"]

[workspace.dependencies]
alloy = { version = "0.6.4", features = ["full"] }
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
foundry-compilers = "0.11.0"
tokio = { version = "1.39.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

zkopml-contracts = { path = "contracts" }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
