[workspace]
resolver = "2"
members = ["bin/*"]

[workspace.dependencies]
anyhow = "1.0.86"
tokio = { version = "1.39.1", features = ["full"] }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
