[package]
name = "zkopml-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
anyhow.workspace = true
clap.workspace = true
ipfs-api-backend-hyper.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true 

zkopml-contracts.workspace = true
zkopml-ml.workspace = true
