[package]
name = "zkopml-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
anyhow.workspace = true
candle-core.workspace = true
candle-onnx.workspace = true
clap.workspace = true
futures-util.workspace = true
ipfs-api-backend-hyper.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true 

sha2.workspace = true

sp1-sdk.workspace = true

zkopml-contracts.workspace = true
zkopml-ml.workspace = true

[build-dependencies]
sp1-build.workspace = true
