[package]
name = "zkopml-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
foundry-compilers.workspace = true

[build-dependencies]
foundry-compilers = { workspace = true }