[package]
name = "zkopml-ml"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
candle-core.workspace = true
candle-onnx.workspace = true
rs_merkle.workspace = true
serde_json.workspace = true

sha2.workspace = true
