[package]
name = "zkopml-ml"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
candle-core.workspace = true
candle-onnx.workspace = true
rs_merkle.workspace = true
serde_json.workspace = true

sha2.workspace = true
